### ISSUE TITLE
Manipulate iframe on same domain?

### ISSUE THREAD

**Issue by kmob2** [Viglino/jCSSRule#1]
Hello,

That's a very nice lightweight jquery script. Thank you!.

I have an iframe that loads content from the same domain. Using the built jquery css, I can do this, which works fine.
`$("iframe").contents().find(".site-header").css("height", "100px");`

How would I do this with your plugin? I tried:
`$("iframe").contents().find(".site-header").cssRule("height", "100px");`

Unfortunately they don't seem to work.

**Comment by Viglino** [comment]
Hello,
The problem is that the css rules are included in the main document and not in the iframe.
Thus elements in the iframe don't access the css of the main frame...
Looking at the code: lines 16-18 create a css in the current frame, if you want to create it to be accessible in the iframe you should append it in the iframe itself.
Something like this should work:
```
var stylesheet = $("<style>")
		.prop("type", "text/css")
		.appendTo($("iframe").contents());
```
